(()=>{'use strict';
const SEED=Array.isArray(window.EMPLOYEE_SEED)?window.EMPLOYEE_SEED:[];
const KEY='ppms_v3_employees', EVAL_KEY='ppms_v3_evaluations', TRAIN_KEY='ppms_v3_training';
const sections=[...new Set(SEED.map(e=>e.section).filter(Boolean))];
let employees=load(KEY,SEED), evaluations=load(EVAL_KEY,[]), training=load(TRAIN_KEY,[]), isAdmin=sessionStorage.getItem('ppms_admin')==='1', current='dashboard';
const pages=[['dashboard','Organization Chart'],['section','Section View'],['sectionChart','Section Organization Chart'],['add','Add Employee'],['search','Search Employee'],['training','Training Plan'],['evaluation','Evaluation / Job Observation'],['exam','Online Examination'],['matrix','Section Skill Matrix'],['gap','Competency Gap Analysis'],['cards','Employee Skill Cards'],['matrixExam','Skill Matrix Exam'],['export','Export Center']];
function load(k,d){try{const x=JSON.parse(localStorage.getItem(k)||'null');return Array.isArray(x)?mergeSeed(x):structuredClone(d)}catch{return structuredClone(d)}}
function mergeSeed(local){const m=new Map(SEED.map(x=>[String(x.id),{...x}]));for(const x of local||[])m.set(String(x.id||crypto.randomUUID()),{...(m.get(String(x.id))||{}),...x});return [...m.values()]}
function save(){localStorage.setItem(KEY,JSON.stringify(employees));localStorage.setItem(EVAL_KEY,JSON.stringify(evaluations));localStorage.setItem(TRAIN_KEY,JSON.stringify(training))}
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function age(start){if(!start)return'-';const a=new Date(start),b=new Date();let y=b.getFullYear()-a.getFullYear(),m=b.getMonth()-a.getMonth();if(m<0){y--;m+=12}return `${y?y+' ปี ':''}${m} เดือน`}
function rank(pos=''){pos=pos.toLowerCase();if(pos.includes('manager'))return'manager';if(pos.includes('engineer'))return'engineer';if(pos.includes('supervisor'))return'supervisor';if(pos.includes('leader'))return'leader';if(pos.includes('technician'))return'technician';if(pos.includes('operator'))return'operator';return'other'}
function avatar(e,lg=false){return e.photoData?`<img class="avatar ${lg?'avatar-lg':''}" src="${e.photoData}" alt="">`:`<div class="avatar ${lg?'avatar-lg':''}">${esc((e.name||'E').replace(/^(MR\.|MS\.|MRS\.)/,'').trim()[0]||'E')}</div>`}
function person(e){return `<div class="person ${rank(e.position)}">${avatar(e)}<b>${esc(e.name)}</b><small>${esc(e.id)}<br>${esc(e.position)}</small></div>`}
function levelName(r){return({manager:'Manager',engineer:'Engineer',supervisor:'Supervisor',leader:'Leader',technician:'Technician',operator:'Operator',other:'Other'})[r]}
function nav(){const n=$('#nav');n.innerHTML=pages.map(([id,t])=>`<button data-page="${id}" class="${id===current?'active':''}">${t}</button>`).join('');n.onclick=e=>{const b=e.target.closest('[data-page]');if(b){current=b.dataset.page;render()}}}
function head(title,sub='',actions=''){return `<div class="page-head"><div><h2>${title}</h2><div>${sub}</div></div><div class="actions no-print">${actions}</div></div>`}
function printBtn(){return `<button data-action="print">พิมพ์ / บันทึก PDF</button>`}
function employeeRows(list){return list.map(e=>`<tr><td>${avatar(e)}</td><td>${esc(e.id)}</td><td>${esc(e.name)}</td><td>${esc(e.phone||'-')}</td><td>${esc(e.section)}</td><td>${esc(e.position)}</td><td>${esc(e.startDate||'-')}</td><td>${esc(age(e.startDate))}</td><td class="no-print"><button data-edit="${esc(e.id)}" class="secondary">แก้ไข</button> <button data-delete="${esc(e.id)}" class="danger">ลบ</button></td></tr>`).join('')}
function dashboard(){const sec=sections.map(s=>{const list=employees.filter(e=>e.section===s);const lv=['manager','engineer','supervisor','leader','technician','operator','other'].map(r=>{const a=list.filter(e=>rank(e.position)===r);return a.length?`<div class="level"><h4>${levelName(r)}</h4><div class="people">${a.map(person).join('')}</div></div>`:''}).join('');return `<section class="section-box"><div class="section-title">${esc(s)}<br><small>${list.length} คน</small></div>${lv}</section>`}).join('');return head('Production Division Organization Chart','แยกตาม Section และระดับตำแหน่ง',printBtn())+`<div class="cards"><div class="card metric">พนักงานทั้งหมด<b>${employees.length}</b></div><div class="card metric">Section<b>${sections.length}</b></div><div class="card metric">พนักงานใหม่เดือนนี้<b>${employees.filter(e=>{const d=new Date(e.startDate);const n=new Date();return d.getMonth()===n.getMonth()&&d.getFullYear()===n.getFullYear()}).length}</b></div><div class="card metric">ผู้ใช้งาน<b>${isAdmin?'Admin':'Viewer'}</b></div></div><div class="org-grid" style="margin-top:14px">${sec}</div>`}
function sectionView(chart=false){const selected=sessionStorage.getItem(chart?'chartSec':'viewSec')||sections[0];const list=employees.filter(e=>e.section===selected);const opts=sections.map(s=>`<option ${s===selected?'selected':''}>${esc(s)}</option>`).join('');let body;if(chart){body=['manager','engineer','supervisor','leader','technician','operator','other'].map(r=>{const a=list.filter(e=>rank(e.position)===r);return a.length?`<div class="level"><h4>${levelName(r)}</h4><div class="people">${a.map(person).join('')}</div></div>`:''}).join('');body=`<div class="panel hierarchy">${body||'<div class="empty">ไม่มีข้อมูล</div>'}</div>`}else body=`<div class="table-wrap"><table><thead><tr><th>รูป</th><th>รหัส</th><th>ชื่อ</th><th>ตำแหน่ง</th><th>วันที่เริ่มงาน</th><th>อายุงาน</th></tr></thead><tbody>${list.map(e=>`<tr><td>${avatar(e)}</td><td>${esc(e.id)}</td><td>${esc(e.name)}</td><td>${esc(e.position)}</td><td>${esc(e.startDate)}</td><td>${esc(age(e.startDate))}</td></tr>`).join('')}</tbody></table></div>`;return head(chart?'Section Organization Chart':'Section View',`${list.length} คน`,printBtn())+`<div class="panel no-print"><label>Section<select id="sectionSelect">${opts}</select></label></div><div style="margin-top:12px">${body}</div>`}
function search(){return head('Search Employee',`ข้อมูลพนักงาน ${employees.length} คน`,`<button data-action="csv">ดาวน์โหลด CSV</button>${printBtn()}`)+`<div class="panel no-print"><input id="q" placeholder="ค้นหา รหัส ชื่อ Section ตำแหน่ง เบอร์โทร"></div><div class="table-wrap"><table><thead><tr><th>รูป</th><th>รหัส</th><th>ชื่อ</th><th>เบอร์โทร</th><th>Section</th><th>ตำแหน่ง</th><th>วันที่เริ่มงาน</th><th>อายุงาน</th><th class="no-print">จัดการ</th></tr></thead><tbody id="empBody">${employeeRows(employees)}</tbody></table></div>`}
function employeeForm(e={}){return `<form id="employeeForm" class="form-grid"><input name="id" value="${esc(e.id||'')}" placeholder="รหัสพนักงาน" required><input name="name" value="${esc(e.name||'')}" placeholder="ชื่อภาษาอังกฤษ" required><input name="thaiName" value="${esc(e.thaiName||'')}" placeholder="ชื่อภาษาไทย"><input name="phone" value="${esc(e.phone||'')}" placeholder="เบอร์โทร"><select name="section">${sections.map(s=>`<option ${s===e.section?'selected':''}>${esc(s)}</option>`).join('')}</select><input name="position" value="${esc(e.position||'Operator')}" placeholder="ตำแหน่ง" required><input type="date" name="startDate" value="${esc(e.startDate||'')}" required><select name="contractType"><option ${e.contractType==='Permanent'?'selected':''}>Permanent</option><option ${e.contractType==='Subcontractor'?'selected':''}>Subcontractor</option></select><label class="full">รูปพนักงาน<input type="file" name="photo" accept="image/*"></label><div class="full actions"><button type="submit">บันทึกข้อมูล</button><button type="button" class="secondary" data-action="close">ยกเลิก</button></div></form>`}
function add(){return head('Add Employee','เพิ่มข้อมูลพนักงานใหม่')+`<div class="panel">${employeeForm()}</div>`}
function trainingPage(){const rows=employees.map(e=>{const next=new Date();next.setMonth(Math.floor(next.getMonth()/3)*3+3,1);return `<tr><td>${esc(e.id)}</td><td>${esc(e.name)}</td><td>${esc(e.section)}</td><td>${esc(e.position)}</td><td>${next.toISOString().slice(0,10)}</td><td>${training.find(x=>x.employeeId===e.id)?.status||'Planned'}</td></tr>`}).join('');return head('Training Plan','แผนการฝึกอบรมรายไตรมาส',`<button data-action="trainingCsv">ดาวน์โหลด CSV</button>${printBtn()}`)+`<div class="table-wrap"><table><thead><tr><th>รหัส</th><th>ชื่อ</th><th>Section</th><th>ตำแหน่ง</th><th>กำหนดครั้งถัดไป</th><th>สถานะ</th></tr></thead><tbody>${rows}</tbody></table></div>`}
function evalPage(){return head('Evaluation / Job Observation','บันทึกผลประเมิน',printBtn())+`<div class="panel no-print"><form id="evalForm" class="form-grid"><select name="employeeId">${employees.map(e=>`<option value="${esc(e.id)}">${esc(e.id)} - ${esc(e.name)}</option>`).join('')}</select><input type="date" name="date" value="${new Date().toISOString().slice(0,10)}"><input type="number" min="0" max="100" name="score" placeholder="คะแนน" required><input name="evaluator" placeholder="ผู้ประเมิน" required><textarea class="full" name="note" placeholder="หมายเหตุ"></textarea><button>บันทึกผลประเมิน</button></form></div><div class="table-wrap" style="margin-top:12px"><table><thead><tr><th>วันที่</th><th>รหัส</th><th>ชื่อ</th><th>คะแนน</th><th>ผล</th><th>ผู้ประเมิน</th><th>หมายเหตุ</th></tr></thead><tbody>${evaluations.map(x=>{const e=employees.find(a=>a.id===x.employeeId)||{};return `<tr><td>${esc(x.date)}</td><td>${esc(x.employeeId)}</td><td>${esc(e.name)}</td><td>${esc(x.score)}</td><td>${+x.score>=70?'PASS':'RE-TRAIN'}</td><td>${esc(x.evaluator)}</td><td>${esc(x.note)}</td></tr>`}).join('')||'<tr><td colspan="7">ยังไม่มีผลประเมิน</td></tr>'}</tbody></table></div>`}
function examPage(){return head('Online Examination','ระบบข้อสอบและผลสอบ')+`<div class="panel"><div class="notice ok">ระบบพร้อมใช้งาน ข้อมูลพนักงานถูกโหลดครบ ${employees.length} คน</div><div class="form-grid"><select>${employees.map(e=>`<option>${esc(e.id)} - ${esc(e.name)}</option>`).join('')}</select><select><option>Q1 Examination</option><option>Q2 Examination</option><option>Q3 Examination</option><option>Q4 Examination</option></select><button onclick="alert('เปิดชุดข้อสอบสำหรับพนักงานที่เลือกแล้ว')">เริ่มข้อสอบ</button></div></div>`}
function matrixPage(gap=false){const skills=['Safety','Quality','Machine Operation','Inspection','5S'];const rows=employees.map(e=>{const lv=e.skillLevels||{};const vals=skills.map(s=>Number(lv[s]||e.currentSkillLevel||1));const avg=vals.reduce((a,b)=>a+b,0)/vals.length;if(gap&&avg>=3)return'';return `<tr><td>${esc(e.id)}</td><td>${esc(e.name)}</td><td>${esc(e.section)}</td>${vals.map(v=>`<td>${v}</td>`).join('')}<td>${avg.toFixed(1)}</td><td>${Math.max(0,3-avg).toFixed(1)}</td></tr>`}).join('');return head(gap?'Competency Gap Analysis':'Section Skill Matrix',gap?'แสดงพนักงานที่ค่าเฉลี่ยต่ำกว่า Level 3':'ระดับทักษะ 1–5',`<button data-action="matrixCsv">ดาวน์โหลด CSV</button>${printBtn()}`)+`<div class="table-wrap"><table><thead><tr><th>รหัส</th><th>ชื่อ</th><th>Section</th>${skills.map(s=>`<th>${s}</th>`).join('')}<th>Average</th><th>Gap to L3</th></tr></thead><tbody>${rows||'<tr><td colspan="10">ไม่พบ Competency Gap</td></tr>'}</tbody></table></div>`}
function cardsPage(){return head('Employee Skill Cards',`${employees.length} ใบ`,printBtn())+`<div class="skill-grid">${employees.map(e=>`<div class="skill-card">${avatar(e,true)}<h3>${esc(e.name)}</h3><div>${esc(e.id)} | ${esc(e.section)}</div><div>${esc(e.position)}</div>${['Safety','Quality','Machine Operation','Inspection','5S'].map(s=>`<div class="skill-row"><span>${s}</span><b>Level ${Number((e.skillLevels||{})[s]||e.currentSkillLevel||1)}</b></div>`).join('')}</div>`).join('')}</div>`}
function exportPage(){return head('Export Center','ดาวน์โหลดและสำรองข้อมูลทั้งหมด')+`<div class="cards"><div class="card"><h3>Employee</h3><button data-action="csv">Employee CSV</button></div><div class="card"><h3>Skill Matrix</h3><button data-action="matrixCsv">Skill Matrix CSV</button></div><div class="card"><h3>Backup</h3><button data-action="backup">Backup JSON</button></div><div class="card"><h3>Print / PDF</h3><button data-action="print">พิมพ์หน้านี้</button></div></div><div class="panel no-print" style="margin-top:12px"><h3>นำเข้าข้อมูลสำรอง</h3><input type="file" id="importJson" accept="application/json"><button data-action="reset" class="danger">คืนค่าข้อมูลเริ่มต้น 116 คน</button></div>`}
function render(){nav();const map={dashboard,section:()=>sectionView(false),sectionChart:()=>sectionView(true),add,search,training:trainingPage,evaluation:evalPage,exam:examPage,matrix:()=>matrixPage(false),gap:()=>matrixPage(true),cards:cardsPage,matrixExam:evalPage,export:exportPage};$('#app').innerHTML=map[current]();bind();updateAuth()}
function bind(){const sel=$('#sectionSelect');if(sel)sel.onchange=()=>{sessionStorage.setItem(current==='sectionChart'?'chartSec':'viewSec',sel.value);render()};const q=$('#q');if(q)q.oninput=()=>{const x=q.value.toLowerCase();$('#empBody').innerHTML=employeeRows(employees.filter(e=>Object.values(e).some(v=>String(v).toLowerCase().includes(x))))};const f=$('#employeeForm');if(f)f.onsubmit=async ev=>{ev.preventDefault();if(!isAdmin)return alert('กรุณา Login เป็น Admin');const fd=new FormData(f),id=String(fd.get('id')).trim();let photo='';const file=fd.get('photo');if(file&&file.size)photo=await toData(file);const old=employees.find(e=>e.id===id);const data={...(old||{}),id,name:String(fd.get('name')).trim().toUpperCase(),thaiName:String(fd.get('thaiName')||'').trim(),phone:String(fd.get('phone')||'').trim(),section:String(fd.get('section')),position:String(fd.get('position')).trim(),startDate:String(fd.get('startDate')),contractType:String(fd.get('contractType')),photoData:photo||(old?.photoData||'')};if(!old)employees.push(data);else Object.assign(old,data);save();alert('บันทึกเรียบร้อย');current='search';render()};const ef=$('#evalForm');if(ef)ef.onsubmit=e=>{e.preventDefault();if(!isAdmin)return alert('กรุณา Login เป็น Admin');const d=Object.fromEntries(new FormData(ef));evaluations.unshift({...d,createdAt:new Date().toISOString()});save();render()};const imp=$('#importJson');if(imp)imp.onchange=async()=>{try{const d=JSON.parse(await imp.files[0].text());if(!Array.isArray(d.employees))throw Error('รูปแบบไฟล์ไม่ถูกต้อง');employees=mergeSeed(d.employees);evaluations=Array.isArray(d.evaluations)?d.evaluations:[];training=Array.isArray(d.training)?d.training:[];save();render();alert('นำเข้าข้อมูลสำเร็จ')}catch(e){alert(e.message)}}}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden');bind()}
function closeModal(){$('#modal').classList.add('hidden')}
function toData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
function dl(name,text,type='text/plain;charset=utf-8'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
function csv(rows){if(!rows.length)return'';const h=Object.keys(rows[0]),q=v=>'"'+String(v??'').replace(/"/g,'""')+'"';return '\ufeff'+[h.map(q).join(','),...rows.map(r=>h.map(k=>q(r[k])).join(','))].join('\r\n')}
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-edit],[data-delete]');if(!b)return;if(b.dataset.page)return;const a=b.dataset.action;if(a==='print')window.print();if(a==='csv')dl('Employee_List.csv',csv(employees.map(e=>({ID:e.id,Name:e.name,ThaiName:e.thaiName||'',Phone:e.phone||'',Section:e.section,Position:e.position,StartDate:e.startDate,Contract:e.contractType||''}))),'text/csv;charset=utf-8');if(a==='trainingCsv')dl('Training_Plan.csv',csv(employees.map(e=>({ID:e.id,Name:e.name,Section:e.section,Position:e.position,Status:'Planned'}))),'text/csv;charset=utf-8');if(a==='matrixCsv')dl('Skill_Matrix.csv',csv(employees.map(e=>({ID:e.id,Name:e.name,Section:e.section,Safety:(e.skillLevels||{}).Safety||e.currentSkillLevel||1,Quality:(e.skillLevels||{}).Quality||e.currentSkillLevel||1,Machine:(e.skillLevels||{})['Machine Operation']||e.currentSkillLevel||1,Inspection:(e.skillLevels||{}).Inspection||e.currentSkillLevel||1,'5S':(e.skillLevels||{})['5S']||e.currentSkillLevel||1}))),'text/csv;charset=utf-8');if(a==='backup')dl('PPMS_Backup.json',JSON.stringify({version:'V300',exportedAt:new Date().toISOString(),employees,evaluations,training},null,2),'application/json');if(a==='reset'&&confirm('คืนค่าข้อมูลเริ่มต้นหรือไม่?')){employees=structuredClone(SEED);evaluations=[];training=[];save();render()}if(a==='close')closeModal();if(b.dataset.edit){if(!isAdmin)return alert('กรุณา Login เป็น Admin');const x=employees.find(e=>e.id===b.dataset.edit);modal('<h2>แก้ไขพนักงาน</h2>'+employeeForm(x))}if(b.dataset.delete){if(!isAdmin)return alert('กรุณา Login เป็น Admin');if(confirm('ลบพนักงานคนนี้หรือไม่?')){employees=employees.filter(x=>x.id!==b.dataset.delete);save();render()}}});
$('#closeModal').onclick=closeModal;$('#loginBtn').onclick=()=>{const p=prompt('รหัสผ่าน Admin');if(p==='1234'){isAdmin=true;sessionStorage.setItem('ppms_admin','1');updateAuth()}else if(p!==null)alert('รหัสผ่านไม่ถูกต้อง')};$('#logoutBtn').onclick=()=>{isAdmin=false;sessionStorage.removeItem('ppms_admin');updateAuth()};
function updateAuth(){$('#modeBadge').textContent=isAdmin?'Admin':'Public Viewer';$('#loginBtn').classList.toggle('hidden',isAdmin);$('#logoutBtn').classList.toggle('hidden',!isAdmin)}
window.addEventListener('error',e=>console.error('APP ERROR',e.error||e.message));window.getAppHealth=()=>({version:'V300',employees:employees.length,sections:new Set(employees.map(e=>e.section)).size,page:current});render();
})();
