(()=>{'use strict';
const SEED=Array.isArray(window.EMPLOYEE_SEED)?window.EMPLOYEE_SEED:[];
const KEY='ppms_v3_employees', EVAL_KEY='ppms_v3_evaluations', TRAIN_KEY='ppms_v3_training';
const sections=[...new Set(SEED.map(e=>e.section).filter(Boolean))];
let employees=loadEmployees(), evaluations=loadArray(EVAL_KEY), training=loadArray(TRAIN_KEY), examResults=loadArray('ppms_v3_exam_results'), isAdmin=sessionStorage.getItem('ppms_admin')==='1', current='dashboard';

const SECTION_SKILLS={
 'Engineering Support Section':['Safety','Quality System','Process Improvement','Drawing / Specification','Problem Solving','Training & Coaching','Project Management'],
 'Support Production Section':['Safety','Document Control','Production Planning','Material Control','ERP / Record','5S','Communication'],
 'Machine Maintenance Section':['Safety','Preventive Maintenance','Breakdown Repair','Electrical','Mechanical','Spare Part Control','5S'],
 'Tooling Maintenance Section':['Safety','Die Maintenance','Grinding','Tool Assembly','Drawing Reading','Troubleshooting','5S'],
 'Sorting Section':['Safety','Visual Inspection','Defect Criteria','Measurement','Traceability','Packing','5S'],
 'Stamping Section':['Safety','Machine Operation','Die Setup','First Piece Inspection','Quality Check','OEE Record','5S'],
 'Welding Section':['Safety','Welding Operation','Jig Setup','Parameter Check','Visual Inspection','Poka-Yoke','5S'],
 'CNC Section':['Safety','Machine Operation','Program Selection','Tool Offset','Measurement','Quality Check','5S'],
 'Tapping Section':['Safety','Machine Operation','Tool Setup','Thread Inspection','Measurement','Quality Check','5S'],
 'Bending Section':['Safety','Machine Operation','Die Setup','Angle Inspection','Measurement','Quality Check','5S']
};
function skillsFor(section){return SECTION_SKILLS[section]||['Safety','Quality','Machine Operation','Inspection','Problem Solving','5S','Training']}
function skillValue(e,skill){return Math.max(1,Math.min(5,Number((e.skillLevels||{})[skill]||e.currentSkillLevel||1)))}
function skillScore(e,skills){return skills.reduce((a,k)=>a+skillValue(e,k),0)*2}
function acceptance(score){if(score>=62)return{level:5,label:'Expert'};if(score>=50)return{level:4,label:'Advanced'};if(score>=38)return{level:3,label:'Qualified'};if(score>=26)return{level:2,label:'Developing'};return{level:1,label:'Beginner'}}
function skillDates(e){const last=e.skillUpdatedAt||new Date().toISOString().slice(0,10),d=new Date(last);if(Number.isNaN(d.getTime()))return{last:'-',next:'-'};d.setMonth(d.getMonth()+3);return{last:String(last).slice(0,10),next:d.toISOString().slice(0,10)}}
function levelLegend(){return `<div class="skill-legend"><span class="lv1">1 Beginner</span><span class="lv2">2 Developing</span><span class="lv3">3 Qualified</span><span class="lv4">4 Advanced</span><span class="lv5">5 Expert</span></div>`}

const pages=[['dashboard','Organization Chart'],['section','Section View'],['sectionChart','Section Organization Chart'],['add','Add Employee'],['search','Search Employee'],['training','Training Plan'],['evaluation','Evaluation / Job Observation'],['exam','Online Examination'],['matrix','Section Skill Matrix'],['gap','Competency Gap Analysis'],['cards','Employee Skill Cards'],['matrixExam','Skill Matrix Exam'],['export','Export Center']];
function loadEmployees(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return Array.isArray(x)?mergeSeed(x):structuredClone(SEED)}catch{return structuredClone(SEED)}}
function loadArray(k){try{const x=JSON.parse(localStorage.getItem(k)||'[]');return Array.isArray(x)?x:[]}catch{return []}}
function mergeSeed(local){const m=new Map(SEED.map(x=>[String(x.id),{...x}]));for(const x of local||[])m.set(String(x.id||crypto.randomUUID()),{...(m.get(String(x.id))||{}),...x});return [...m.values()]}
function save(){localStorage.setItem(KEY,JSON.stringify(employees));localStorage.setItem(EVAL_KEY,JSON.stringify(evaluations));localStorage.setItem(TRAIN_KEY,JSON.stringify(training));localStorage.setItem('ppms_v3_exam_results',JSON.stringify(examResults));status('บันทึกข้อมูลเรียบร้อย','ok')}
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function age(start){if(!start)return'-';const a=new Date(start),b=new Date();let y=b.getFullYear()-a.getFullYear(),m=b.getMonth()-a.getMonth();if(m<0){y--;m+=12}return `${y?y+' ปี ':''}${m} เดือน`}
function rank(pos=''){pos=pos.toLowerCase();if(pos.includes('manager'))return'manager';if(pos.includes('engineer'))return'engineer';if(pos.includes('supervisor'))return'supervisor';if(pos.includes('leader'))return'leader';if(pos.includes('technician'))return'technician';if(pos.includes('operator'))return'operator';return'other'}
function avatar(e,lg=false){return e.photoData?`<img class="avatar ${lg?'avatar-lg':''}" src="${e.photoData}" alt="">`:`<div class="avatar ${lg?'avatar-lg':''}">${esc((e.name||'E').replace(/^(MR\.|MS\.|MRS\.)/,'').trim()[0]||'E')}</div>`}
function person(e){return `<div class="person ${rank(e.position)}">${avatar(e)}<b>${esc(e.name)}</b><small>${esc(e.id)}<br>${esc(e.position)}</small></div>`}
function levelName(r){return({manager:'Manager',engineer:'Engineer',supervisor:'Supervisor',leader:'Leader',technician:'Technician',operator:'Operator',other:'Other'})[r]}
function nav(){const n=$('#nav');n.innerHTML=pages.map(([id,t])=>`<button data-page="${id}" class="${id===current?'active':''}">${t}</button>`).join('');n.onclick=e=>{const b=e.target.closest('[data-page]');if(b){current=b.dataset.page;render()}}}
function head(title,sub='',actions=''){return `<div class="page-head"><div><h2>${title}</h2><div>${sub}</div></div><div class="actions no-print">${actions}</div></div>`}
function printBtn(){return `<button data-action="printSettings">ตั้งค่าพิมพ์ / บันทึก PDF</button>`}
function downloadBtn(action='currentCsv'){return `<button data-action="${action}">ดาวน์โหลดข้อมูล</button>`}
function employeeRows(list){return list.map(e=>`<tr><td>${avatar(e)}</td><td>${esc(e.id)}</td><td>${esc(e.name)}</td><td>${esc(e.phone||'-')}</td><td>${esc(e.section)}</td><td>${esc(e.position)}</td><td>${esc(e.startDate||'-')}</td><td>${esc(age(e.startDate))}</td><td class="no-print"><button data-edit="${esc(e.id)}" class="secondary">แก้ไข</button> <button data-delete="${esc(e.id)}" class="danger">ลบ</button></td></tr>`).join('')}
function dashboard(){const sec=sections.map(s=>{const list=employees.filter(e=>e.section===s);const lv=['manager','engineer','supervisor','leader','technician','operator','other'].map(r=>{const a=list.filter(e=>rank(e.position)===r);return a.length?`<div class="level"><h4>${levelName(r)}</h4><div class="people">${a.map(person).join('')}</div></div>`:''}).join('');return `<section class="section-box"><div class="section-title">${esc(s)}<br><small>${list.length} คน</small></div>${lv}</section>`}).join('');return head('Production Division Organization Chart','แยกตาม Section และระดับตำแหน่ง',printBtn())+`<div class="cards"><div class="card metric">พนักงานทั้งหมด<b>${employees.length}</b></div><div class="card metric">Section<b>${sections.length}</b></div><div class="card metric">พนักงานใหม่เดือนนี้<b>${employees.filter(e=>{const d=new Date(e.startDate);const n=new Date();return d.getMonth()===n.getMonth()&&d.getFullYear()===n.getFullYear()}).length}</b></div><div class="card metric">ผู้ใช้งาน<b>${isAdmin?'Admin':'Viewer'}</b></div></div><div class="org-grid" style="margin-top:14px">${sec}</div>`}
function sectionView(chart=false){const selected=sessionStorage.getItem(chart?'chartSec':'viewSec')||sections[0];const list=employees.filter(e=>e.section===selected);const opts=sections.map(s=>`<option ${s===selected?'selected':''}>${esc(s)}</option>`).join('');let body;if(chart){body=['manager','engineer','supervisor','leader','technician','operator','other'].map(r=>{const a=list.filter(e=>rank(e.position)===r);return a.length?`<div class="level"><h4>${levelName(r)}</h4><div class="people">${a.map(person).join('')}</div></div>`:''}).join('');body=`<div class="panel hierarchy">${body||'<div class="empty">ไม่มีข้อมูล</div>'}</div>`}else body=`<div class="table-wrap"><table><thead><tr><th>รูป</th><th>รหัส</th><th>ชื่อ</th><th>ตำแหน่ง</th><th>วันที่เริ่มงาน</th><th>อายุงาน</th></tr></thead><tbody>${list.map(e=>`<tr><td>${avatar(e)}</td><td>${esc(e.id)}</td><td>${esc(e.name)}</td><td>${esc(e.position)}</td><td>${esc(e.startDate)}</td><td>${esc(age(e.startDate))}</td></tr>`).join('')}</tbody></table></div>`;return head(chart?'Section Organization Chart':'Section View',`${list.length} คน`,printBtn())+`<div class="panel no-print"><label>Section<select id="sectionSelect">${opts}</select></label></div><div style="margin-top:12px">${body}</div>`}
function search(){return head('Search Employee',`ข้อมูลพนักงาน ${employees.length} คน`,`<button data-action="csv">ดาวน์โหลด CSV</button>${printBtn()}`)+`<div class="panel no-print"><input id="q" placeholder="ค้นหา รหัส ชื่อ Section ตำแหน่ง เบอร์โทร"></div><div class="table-wrap"><table><thead><tr><th>รูป</th><th>รหัส</th><th>ชื่อ</th><th>เบอร์โทร</th><th>Section</th><th>ตำแหน่ง</th><th>วันที่เริ่มงาน</th><th>อายุงาน</th><th class="no-print">จัดการ</th></tr></thead><tbody id="empBody">${employeeRows(employees)}</tbody></table></div>`}
function employeeForm(e={}){return `<form id="employeeForm" class="form-grid"><input name="id" value="${esc(e.id||'')}" placeholder="รหัสพนักงาน" required><input name="name" value="${esc(e.name||'')}" placeholder="ชื่อภาษาอังกฤษ" required><input name="thaiName" value="${esc(e.thaiName||'')}" placeholder="ชื่อภาษาไทย"><input name="phone" value="${esc(e.phone||'')}" placeholder="เบอร์โทร"><select name="section">${sections.map(s=>`<option ${s===e.section?'selected':''}>${esc(s)}</option>`).join('')}</select><input name="position" value="${esc(e.position||'Operator')}" placeholder="ตำแหน่ง" required><input type="date" name="startDate" value="${esc(e.startDate||'')}" required><select name="contractType"><option ${e.contractType==='Permanent'?'selected':''}>Permanent</option><option ${e.contractType==='Subcontractor'?'selected':''}>Subcontractor</option></select><label class="full">รูปพนักงาน<input type="file" name="photo" accept="image/*"></label><div class="full actions"><button type="submit">บันทึกข้อมูล</button><button type="button" class="secondary" data-action="close">ยกเลิก</button></div></form>`}
function add(){return head('Add Employee','เพิ่มข้อมูลพนักงานใหม่')+`<div class="panel">${employeeForm()}</div>`}
function trainingPage(){const rows=employees.map(e=>{const next=new Date();next.setMonth(Math.floor(next.getMonth()/3)*3+3,1);return `<tr><td>${esc(e.id)}</td><td>${esc(e.name)}</td><td>${esc(e.section)}</td><td>${esc(e.position)}</td><td>${next.toISOString().slice(0,10)}</td><td>${training.find(x=>x.employeeId===e.id)?.status||'Planned'}</td></tr>`}).join('');return head('Training Plan','แผนการฝึกอบรมรายไตรมาส',`<button data-action="trainingCsv">ดาวน์โหลด CSV</button>${printBtn()}`)+`<div class="table-wrap"><table><thead><tr><th>รหัส</th><th>ชื่อ</th><th>Section</th><th>ตำแหน่ง</th><th>กำหนดครั้งถัดไป</th><th>สถานะ</th></tr></thead><tbody>${rows}</tbody></table></div>`}
function evalPage(){return head('Evaluation / Job Observation','บันทึกผลประเมิน',printBtn())+`<div class="panel no-print"><form id="evalForm" class="form-grid"><select name="employeeId">${employees.map(e=>`<option value="${esc(e.id)}">${esc(e.id)} - ${esc(e.name)}</option>`).join('')}</select><input type="date" name="date" value="${new Date().toISOString().slice(0,10)}"><input type="number" min="0" max="100" name="score" placeholder="คะแนน" required><input name="evaluator" placeholder="ผู้ประเมิน" required><textarea class="full" name="note" placeholder="หมายเหตุ"></textarea><button>บันทึกผลประเมิน</button></form></div><div class="table-wrap" style="margin-top:12px"><table><thead><tr><th>วันที่</th><th>รหัส</th><th>ชื่อ</th><th>คะแนน</th><th>ผล</th><th>ผู้ประเมิน</th><th>หมายเหตุ</th></tr></thead><tbody>${evaluations.map(x=>{const e=employees.find(a=>a.id===x.employeeId)||{};return `<tr><td>${esc(x.date)}</td><td>${esc(x.employeeId)}</td><td>${esc(e.name)}</td><td>${esc(x.score)}</td><td>${+x.score>=70?'PASS':'RE-TRAIN'}</td><td>${esc(x.evaluator)}</td><td>${esc(x.note)}</td></tr>`}).join('')||'<tr><td colspan="7">ยังไม่มีผลประเมิน</td></tr>'}</tbody></table></div>`}
function examPage(){const rows=examResults.map(x=>{const e=employees.find(a=>String(a.id)===String(x.employeeId))||{};return `<tr><td>${esc(x.date)}</td><td>${esc(x.employeeId)}</td><td>${esc(e.name||'')}</td><td>${esc(x.quarter)}</td><td>${esc(x.score)}%</td><td>${x.score>=80?'PASS':'RE-TRAIN'}</td></tr>`}).join('');return head('Online Examination','ระบบข้อสอบและผลสอบ',downloadBtn('examCsv')+printBtn())+`<div class="panel no-print"><form id="examForm" class="form-grid"><select name="employeeId">${employees.map(e=>`<option value="${esc(e.id)}">${esc(e.id)} - ${esc(e.name)}</option>`).join('')}</select><select name="quarter"><option>Q1</option><option>Q2</option><option>Q3</option><option>Q4</option></select><input name="evaluator" placeholder="ผู้ประเมิน" required><div class="full exam-question"><b>1. ต้องตรวจสอบความปลอดภัยก่อนเริ่มงานหรือไม่?</b><label><input type="radio" name="q1" value="1" required> ใช่</label><label><input type="radio" name="q1" value="0"> ไม่ใช่</label></div><div class="full exam-question"><b>2. ต้องบันทึกผลการตรวจ First Piece หรือไม่?</b><label><input type="radio" name="q2" value="1" required> ใช่</label><label><input type="radio" name="q2" value="0"> ไม่ใช่</label></div><button>ส่งข้อสอบ</button></form></div><div class="table-wrap" style="margin-top:12px"><table><thead><tr><th>วันที่</th><th>รหัส</th><th>ชื่อ</th><th>Quarter</th><th>คะแนน</th><th>ผล</th></tr></thead><tbody>${rows||'<tr><td colspan="6">ยังไม่มีผลสอบ</td></tr>'}</tbody></table></div>`}
function matrixPage(gap=false){
 const selected=sessionStorage.getItem('matrixSec')||sections[0];
 const skills=skillsFor(selected),list=employees.filter(e=>e.section===selected);
 const rows=list.map((e,i)=>{const vals=skills.map(k=>skillValue(e,k)),score=skillScore(e,skills),a=acceptance(score),avg=vals.reduce((x,y)=>x+y,0)/vals.length;if(gap&&avg>=3)return'';return `<tr><td>${i+1}</td><td>${avatar(e)}</td><td>${esc(e.id)}</td><td class="emp-col"><b>${esc(e.name)}</b><small>${esc(e.position)}</small></td>${skills.map((k,j)=>`<td><span class="level-box level-${vals[j]}">${vals[j]}</span></td>`).join('')}<td class="score-cell">${score}</td><td><span class="rank-badge rank-${a.level}">Level ${a.level}<small>${a.label}</small></span></td></tr>`}).join('');
 const opts=sections.map(x=>`<option ${x===selected?'selected':''}>${esc(x)}</option>`).join('');
 return head(gap?'Competency Gap Analysis':'Section Skill Matrix',`${esc(selected)} · ${list.length} คน`,`<button data-action="matrixCsv">ดาวน์โหลด CSV</button>${printBtn()}`)+`<div class="panel no-print matrix-filter"><label>เลือก Section<select id="matrixSection">${opts}</select></label></div><section class="matrix-report"><div class="report-title"><div class="report-logo">JR</div><div><h2>SECTION SKILL MATRIX</h2><p>Production People Management System</p></div><div class="doc-box">Revision: 00<br>Update: Quarterly</div></div>${levelLegend()}<div class="table-wrap skill-table-wrap"><table class="skill-matrix-table"><thead><tr><th>No.</th><th>Photo</th><th>Emp.ID</th><th class="emp-col">Name / Position</th>${skills.map(k=>`<th>${esc(k)}<small>Level 1–5</small></th>`).join('')}<th>Score<small>14–70</small></th><th>Acceptance</th></tr></thead><tbody>${rows||`<tr><td colspan="${skills.length+7}" class="empty">${gap?'ไม่พบ Competency Gap':'ไม่มีข้อมูลพนักงาน'}</td></tr>`}</tbody></table></div><div class="criteria-grid"><div><b>Acceptance Criteria</b><span>Level 1: 14–25</span><span>Level 2: 26–37</span><span>Level 3: 38–49</span><span>Level 4: 50–61</span><span>Level 5: 62–70</span></div><div><b>Skill Level Description</b><span>1 = เรียนรู้ / ต้องมีผู้ควบคุม</span><span>2 = ปฏิบัติได้บางส่วน</span><span>3 = ปฏิบัติงานได้ตามมาตรฐาน</span><span>4 = แก้ปัญหาและสอนงานได้</span><span>5 = ผู้เชี่ยวชาญ / ปรับปรุงกระบวนการได้</span></div></div><div class="signature-row"><div>Prepared by<br><br>________________</div><div>Reviewed by<br><br>________________</div><div>Approved by<br><br>________________</div></div></section>`}
function cardsPage(){
 const selected=sessionStorage.getItem('cardEmp')||employees[0]?.id||'';
 const e=employees.find(x=>x.id===selected)||employees[0];if(!e)return head('Employee Skill Cards')+'<div class="empty">ไม่มีข้อมูล</div>';
 const skills=skillsFor(e.section),score=skillScore(e,skills),a=acceptance(score),dates=skillDates(e);
 const opts=employees.map(x=>`<option value="${esc(x.id)}" ${x.id===e.id?'selected':''}>${esc(x.id)} - ${esc(x.name)}</option>`).join('');
 return head('Employee Skill Card',`${esc(e.id)} · ${esc(e.name)}`,printBtn())+`<div class="panel no-print card-filter"><label>เลือกพนักงาน<select id="cardEmployee">${opts}</select></label></div><section class="employee-skill-card"><div class="skill-card-banner"><div class="report-logo">JR</div><div><h2>EMPLOYEE SKILL CARD</h2><p>Production Division</p></div><span class="rank-badge rank-${a.level}">LEVEL ${a.level}<small>${a.label}</small></span></div><div class="employee-profile">${avatar(e,true)}<div><h1>${esc(e.name)}</h1><p>${esc(e.thaiName||'')}</p><div class="profile-grid"><span><b>Emp.ID</b>${esc(e.id)}</span><span><b>Position</b>${esc(e.position)}</span><span><b>Section</b>${esc(e.section)}</span><span><b>Start Date</b>${esc(e.startDate||'-')}</span><span><b>Last Update</b>${esc(dates.last)}</span><span><b>Next Update</b>${esc(dates.next)}</span></div></div><div class="score-circle"><small>Total Score</small><strong>${score}</strong><span>/ 70</span></div></div>${levelLegend()}<div class="skill-bars">${skills.map(k=>{const v=skillValue(e,k);return `<div class="skill-bar-row"><b>${esc(k)}</b><div class="skill-track"><i style="width:${v*20}%"></i></div><span class="level-box level-${v}">${v}</span></div>`}).join('')}</div><div class="card-footer"><div><b>Acceptance:</b> ${a.label} (Level ${a.level})</div><div><b>Approved by:</b> Production Manager</div></div><div class="signature-row"><div>Employee<br><br>________________</div><div>Evaluator<br><br>________________</div><div>Manager<br><br>________________</div></div></section>`}
function exportPage(){return head('Export Center','ดาวน์โหลดและสำรองข้อมูลทั้งหมด')+`<div class="download-grid"><div class="card"><h3>Employee</h3><button data-action="csv">Employee CSV</button><button data-action="sectionCsv">Section CSV</button></div><div class="card"><h3>Skill Matrix</h3><button data-action="matrixCsv">Skill Matrix CSV</button><button data-action="cardCsv">Skill Card CSV</button></div><div class="card"><h3>Training / Evaluation</h3><button data-action="trainingCsv">Training CSV</button><button data-action="evaluationCsv">Evaluation CSV</button><button data-action="examCsv">Exam CSV</button></div><div class="card"><h3>Backup</h3><button data-action="backup">Backup JSON</button><button data-action="printSettings">ตั้งค่าพิมพ์ / PDF</button></div></div><div class="panel no-print" style="margin-top:12px"><h3>นำเข้าข้อมูลสำรอง</h3><input type="file" id="importJson" accept="application/json"><button data-action="reset" class="danger">คืนค่าข้อมูลเริ่มต้น 116 คน</button></div>`}
function render(){nav();const map={dashboard,section:()=>sectionView(false),sectionChart:()=>sectionView(true),add,search,training:trainingPage,evaluation:evalPage,exam:examPage,matrix:()=>matrixPage(false),gap:()=>matrixPage(true),cards:cardsPage,matrixExam:evalPage,export:exportPage};try{$('#app').innerHTML=(map[current]||dashboard)();bind();enhanceSelects();updateAuth()}catch(err){console.error(err);$('#app').innerHTML=`<div class="page-error"><h2>ไม่สามารถแสดงหน้านี้ได้</h2><p>${esc(err.message)}</p><button data-page="dashboard">กลับหน้าหลัก</button></div>`;status('เกิดข้อผิดพลาด: '+err.message,'error')}}
function bind(){const ms=$('#matrixSection');if(ms)ms.onchange=()=>{sessionStorage.setItem('matrixSec',ms.value);render()};const ce=$('#cardEmployee');if(ce)ce.onchange=()=>{sessionStorage.setItem('cardEmp',ce.value);render()};const sel=$('#sectionSelect');if(sel)sel.onchange=()=>{sessionStorage.setItem(current==='sectionChart'?'chartSec':'viewSec',sel.value);render()};const q=$('#q');if(q)q.oninput=()=>{const x=q.value.toLowerCase();$('#empBody').innerHTML=employeeRows(employees.filter(e=>Object.values(e).some(v=>String(v).toLowerCase().includes(x))))};const f=$('#employeeForm');if(f)f.onsubmit=async ev=>{ev.preventDefault();if(!isAdmin)return alert('กรุณา Login เป็น Admin');const fd=new FormData(f),id=String(fd.get('id')).trim();let photo='';const file=fd.get('photo');if(file&&file.size)photo=await toData(file);const old=employees.find(e=>e.id===id);const data={...(old||{}),id,name:String(fd.get('name')).trim().toUpperCase(),thaiName:String(fd.get('thaiName')||'').trim(),phone:String(fd.get('phone')||'').trim(),section:String(fd.get('section')),position:String(fd.get('position')).trim(),startDate:String(fd.get('startDate')),contractType:String(fd.get('contractType')),photoData:photo||(old?.photoData||'')};if(!old)employees.push(data);else Object.assign(old,data);save();alert('บันทึกเรียบร้อย');current='search';render()};const ef=$('#evalForm');if(ef)ef.onsubmit=e=>{e.preventDefault();if(!isAdmin)return alert('กรุณา Login เป็น Admin');const d=Object.fromEntries(new FormData(ef));evaluations.unshift({...d,createdAt:new Date().toISOString()});save();render()};const xf=$('#examForm');if(xf)xf.onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(xf));const score=(Number(d.q1)+Number(d.q2))*50;examResults.unshift({employeeId:d.employeeId,quarter:d.quarter,evaluator:d.evaluator,score,date:new Date().toISOString().slice(0,10)});save();render()};const imp=$('#importJson');if(imp)imp.onchange=async()=>{try{const d=JSON.parse(await imp.files[0].text());if(!Array.isArray(d.employees))throw Error('รูปแบบไฟล์ไม่ถูกต้อง');employees=mergeSeed(d.employees);evaluations=Array.isArray(d.evaluations)?d.evaluations:[];training=Array.isArray(d.training)?d.training:[];examResults=Array.isArray(d.examResults)?d.examResults:[];save();render();alert('นำเข้าข้อมูลสำเร็จ')}catch(e){alert(e.message)}}}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden');bind()}
function closeModal(){$('#modal').classList.add('hidden')}
function toData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
function dl(name,text,type='text/plain;charset=utf-8'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
function csv(rows){if(!rows.length)return'';const h=Object.keys(rows[0]),q=v=>'"'+String(v??'').replace(/"/g,'""')+'"';return '\ufeff'+[h.map(q).join(','),...rows.map(r=>h.map(k=>q(r[k])).join(','))].join('\r\n')}
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-edit],[data-delete]');if(!b)return;if(b.dataset.page)return;const a=b.dataset.action;if(a==='print')window.print();if(a==='csv')dl('Employee_List.csv',csv(employees.map(e=>({ID:e.id,Name:e.name,ThaiName:e.thaiName||'',Phone:e.phone||'',Section:e.section,Position:e.position,StartDate:e.startDate,Contract:e.contractType||''}))),'text/csv;charset=utf-8');if(a==='trainingCsv')dl('Training_Plan.csv',csv(employees.map(e=>({ID:e.id,Name:e.name,Section:e.section,Position:e.position,Status:'Planned'}))),'text/csv;charset=utf-8');if(a==='matrixCsv')dl('Skill_Matrix.csv',csv(employees.map(e=>({ID:e.id,Name:e.name,Section:e.section,Safety:(e.skillLevels||{}).Safety||e.currentSkillLevel||1,Quality:(e.skillLevels||{}).Quality||e.currentSkillLevel||1,Machine:(e.skillLevels||{})['Machine Operation']||e.currentSkillLevel||1,Inspection:(e.skillLevels||{}).Inspection||e.currentSkillLevel||1,'5S':(e.skillLevels||{})['5S']||e.currentSkillLevel||1}))),'text/csv;charset=utf-8');if(a==='backup')dl('PPMS_Backup.json',JSON.stringify({version:'V302',exportedAt:new Date().toISOString(),employees,evaluations,training,examResults},null,2),'application/json');if(a==='reset'&&confirm('คืนค่าข้อมูลเริ่มต้นหรือไม่?')){employees=structuredClone(SEED);evaluations=[];training=[];save();render()}if(a==='close')closeModal();if(b.dataset.edit){if(!isAdmin)return alert('กรุณา Login เป็น Admin');const x=employees.find(e=>e.id===b.dataset.edit);modal('<h2>แก้ไขพนักงาน</h2>'+employeeForm(x))}if(b.dataset.delete){if(!isAdmin)return alert('กรุณา Login เป็น Admin');if(confirm('ลบพนักงานคนนี้หรือไม่?')){employees=employees.filter(x=>x.id!==b.dataset.delete);save();render()}}});
$('#closeModal').onclick=closeModal;$('#loginBtn').onclick=()=>{const p=prompt('รหัสผ่าน Admin');if(p==='1234'){isAdmin=true;sessionStorage.setItem('ppms_admin','1');updateAuth()}else if(p!==null)alert('รหัสผ่านไม่ถูกต้อง')};$('#logoutBtn').onclick=()=>{isAdmin=false;sessionStorage.removeItem('ppms_admin');updateAuth()};
function updateAuth(){$('#modeBadge').textContent=isAdmin?'Admin':'Public Viewer';$('#loginBtn').classList.toggle('hidden',isAdmin);$('#logoutBtn').classList.toggle('hidden',!isAdmin)}
window.addEventListener('error',e=>{console.error('APP ERROR',e.error||e.message);status('ตรวจพบข้อผิดพลาด: '+(e.message||'Unknown'),'error')});
function status(message,type='ok'){
 let x=document.getElementById('statusbar');if(!x){x=document.createElement('div');x.id='statusbar';x.className='statusbar';document.body.appendChild(x)}
 x.textContent=message;x.className='statusbar '+type;clearTimeout(status.timer);status.timer=setTimeout(()=>x.remove(),2600);
}
function enhanceSelects(){
 document.querySelectorAll('#app select').forEach((sel,i)=>{
  if(sel.dataset.searchReady==='1'||sel.options.length<8)return;sel.dataset.searchReady='1';
  const input=document.createElement('input');input.type='search';input.className='select-search no-print';input.placeholder='ค้นหาใน Dropdown...';
  const all=[...sel.options].map(o=>({value:o.value,text:o.text,selected:o.selected}));
  input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase(),value=sel.value;sel.innerHTML='';all.filter(o=>!q||o.text.toLowerCase().includes(q)||String(o.value).toLowerCase().includes(q)).forEach(o=>sel.add(new Option(o.text,o.value,false,o.value===value)));if(!sel.options.length)sel.add(new Option('ไม่พบข้อมูล',''));});
  sel.parentNode.insertBefore(input,sel);
 });
}
function printSettings(){
 modal(`<h2>ตั้งค่าการพิมพ์ / Save as PDF</h2><div class="print-settings"><label>ขนาดกระดาษ<select id="paperSize"><option>A4</option><option>A3</option></select></label><label>แนวกระดาษ<select id="paperOrientation"><option value="portrait">แนวตั้ง</option><option value="landscape">แนวนอน</option></select></label><label>ขนาดเนื้อหา<select id="paperScale"><option>70</option><option>80</option><option>90</option><option selected>100</option><option>110</option><option>120</option></select></label></div><p>หลังจากกดพิมพ์ สามารถเลือกเครื่องพิมพ์ หรือ Save as PDF ได้</p><div class="actions"><button id="doPrint">พิมพ์ตอนนี้</button><button class="secondary" data-action="close">ยกเลิก</button></div>`);
 const btn=document.getElementById('doPrint');if(btn)btn.onclick=()=>{const size=document.getElementById('paperSize').value,orientation=document.getElementById('paperOrientation').value,scale=document.getElementById('paperScale').value;let st=document.getElementById('dynamicPrintStyle');if(!st){st=document.createElement('style');st.id='dynamicPrintStyle';document.head.appendChild(st)}st.textContent=`@page{size:${size} ${orientation};margin:8mm}`;document.body.className=document.body.className.replace(/print-scale-\d+/g,'').trim()+` print-scale-${scale}`;closeModal();setTimeout(()=>window.print(),100)};
}
function employeeExportRows(list=employees){return list.map(e=>({ID:e.id,Name:e.name,ThaiName:e.thaiName||'',Phone:e.phone||'',Section:e.section,Position:e.position,StartDate:e.startDate||'',Contract:e.contractType||'',Shift:e.shift||''}))}
function skillExportRows(list=employees){return list.map(e=>{const skills=skillsFor(e.section),row={ID:e.id,Name:e.name,Section:e.section,Position:e.position};skills.forEach(k=>row[k]=skillValue(e,k));row.Score=skillScore(e,skills);row.Acceptance=acceptance(row.Score).label;return row})}
function currentRows(){
 if(current==='training')return employees.map(e=>({ID:e.id,Name:e.name,Section:e.section,Position:e.position,Status:training.find(x=>String(x.employeeId)===String(e.id))?.status||'Planned'}));
 if(current==='evaluation'||current==='matrixExam')return evaluations.map(x=>({Date:x.date,EmployeeID:x.employeeId,Score:x.score,Result:Number(x.score)>=70?'PASS':'RE-TRAIN',Evaluator:x.evaluator,Note:x.note||''}));
 if(current==='exam')return examResults;
 if(current==='matrix'||current==='gap'||current==='cards')return skillExportRows();
 const sec=sessionStorage.getItem(current==='sectionChart'?'chartSec':'viewSec');return employeeExportRows(sec?employees.filter(e=>e.section===sec):employees);
}
document.addEventListener('click',e=>{
 const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;
 if(a==='printSettings'){e.preventDefault();printSettings()}
 if(a==='currentCsv'){e.preventDefault();dl(`${current}_Data.csv`,csv(currentRows()),'text/csv;charset=utf-8');status('ดาวน์โหลดข้อมูลแล้ว')}
 if(a==='sectionCsv'){e.preventDefault();const sec=sessionStorage.getItem('viewSec')||sections[0];dl(`${sec}_Employees.csv`,csv(employeeExportRows(employees.filter(x=>x.section===sec))),'text/csv;charset=utf-8')}
 if(a==='cardCsv'){e.preventDefault();const id=sessionStorage.getItem('cardEmp'),list=id?employees.filter(x=>String(x.id)===String(id)):employees;dl('Employee_Skill_Card.csv',csv(skillExportRows(list)),'text/csv;charset=utf-8')}
 if(a==='evaluationCsv'){e.preventDefault();dl('Evaluation_Results.csv',csv(evaluations),'text/csv;charset=utf-8')}
 if(a==='examCsv'){e.preventDefault();dl('Online_Exam_Results.csv',csv(examResults),'text/csv;charset=utf-8')}
},true);
window.addEventListener('unhandledrejection',e=>{console.error('PROMISE ERROR',e.reason);status('ระบบพบข้อผิดพลาด แต่ยังใช้งานหน้าปัจจุบันได้','error')});
window.getAppHealth=()=>({version:'V302',employees:employees.length,sections:new Set(employees.map(e=>e.section)).size,page:current});render();
})();
