
(function(){
'use strict';
function companyLogo(){var el=document.querySelector('.company-logo');return el&&el.src?el.src:'';}
function currentEvaluator(){var badge=document.getElementById('userBadge'),txt=badge?String(badge.textContent||'').trim():'';return txt&&txt!=='Public Viewer'?txt:'Section Engineering';}
window.skillMatrixHeader=function(section){var quarter=(window.smQuarter&&smQuarter.value&&smQuarter.value!=='AUTO')?smQuarter.value:(typeof quarterOf==='function'?quarterOf():'');var logo=companyLogo();return '<div class="matrix-report-head">'+(logo?'<img class="matrix-company-logo" src="'+logo+'" alt="JINRONG logo">':'<div class="matrix-company-logo"></div>')+'<div class="matrix-title-block"><h1>SKILL MATRIX — '+esc(section)+'</h1><div class="matrix-subtitle">Employee Competency & Skill Evaluation · มาตรฐาน 5 ระดับ (1–5) · คะแนนรวม 14–70 คะแนน</div></div><div class="matrix-dept-block"><b>JINRONG TL</b><span>Production Division</span><span>รอบ '+esc(quarter)+'</span></div></div><div class="matrix-info-strip"><div><b>Section</b><span>'+esc(section)+'</span></div><div><b>วันที่ประเมิน</b><span>'+new Date().toLocaleDateString('th-TH')+'</span></div><div><b>ผู้ประเมิน</b><span>'+esc(currentEvaluator())+'</span></div></div>';};
window.renderSearch=function(){var inputEl=document.getElementById('searchInput'),resultsEl=document.getElementById('results');if(!inputEl||!resultsEl)return;var q=normalizeEmployeeSearchText(inputEl.value),terms=q.split(' ').filter(Boolean);var filtered=employees.map(function(e,originalIndex){return Object.assign({},e,{originalIndex:originalIndex});}).filter(function(e){if(!terms.length)return true;var section=normalizeEmployeeSearchText(e.section),searchableText=normalizeEmployeeSearchText([e.id,e.name,e.phone,e.section,e.position,e.startDate,fmt(e.startDate),yearsService(e.startDate),section.replace(/\bsection\b/g,'').replace(/แผนก/g,'')].join(' '));return terms.every(function(term){var core=normalizeEmployeeSearchText(term.replace(/\bsection\b/g,'').replace(/แผนก/g,''));return searchableText.includes(term)||(core&&searchableText.includes(core));});});var list=sortEmployeesStandard(filtered);resultsEl.innerHTML=list.length?list.map(function(e){var key=e.docId||e.id||String(e.originalIndex),safeKey=encodeURIComponent(key);return '<tr><td>'+avatar(e,true)+'</td><td>'+(e.id||'')+'</td><td>'+(e.name||'')+'</td><td>'+(e.phone||'-')+'</td><td>'+(e.section||'')+'</td><td>'+(e.position||'')+'</td><td>'+fmt(e.startDate)+'</td><td>'+yearsService(e.startDate)+'</td><td class="admin-col '+(isAdmin?'':'hidden')+'"><button type="button" class="btn js-edit-employee" data-key="'+safeKey+'" style="margin:2px">แก้ไขข้อมูล</button><button type="button" class="btn secondary js-change-photo" data-key="'+safeKey+'" style="margin:2px">เปลี่ยนรูป</button><button type="button" class="btn danger js-delete-employee" data-key="'+safeKey+'" style="margin:2px">ลบ</button></td></tr>';}).join(''):'<tr><td colspan="9" class="empty">ไม่พบข้อมูล</td></tr>';};
window.exportSkillMatrixRows=function(){var rows=[];sortEmployeesStandard(employees).forEach(function(e){var lv=employeeSkillLevels(e),skills=Object.keys(lv),acc=employeeAcceptance(e,skills);Object.entries(lv).forEach(function(pair){rows.push({'Employee ID':e.id||'','Name':e.name||'','Section':e.section||'','Position':e.position||'','Start Date':e.startDate||'','Skill':pair[0],'Level':Number(pair[1])||1,'Total Skill Score':acc.score==null?'':acc.score,'Acceptance Level':acc.level?'A'+acc.level:'','Work Authorization':acc.work||'รอผลการประเมิน','Last Update':e.skillUpdatedAt||'','Approved By':e.skillApprovedBy||''});});});return rows;};
window.exportMatrixTable=function(section){var list=sortEmployeesStandard(employees.filter(function(e){return e.section===section;}));return '<div style="page-break-after:always">'+skillMatrixHTML(section,list,false)+'</div>';};
function refresh(){try{if(typeof renderSectionSkillMatrix==='function')renderSectionSkillMatrix();if(typeof renderSearch==='function')renderSearch();if(typeof refreshSkillCardEmployees==='function')refreshSkillCardEmployees();if(typeof renderAllOrganizationChart==='function')renderAllOrganizationChart();}catch(err){console.error('V127 refresh failed:',err);}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(refresh,300);});else setTimeout(refresh,300);
})();
